project/models.py
# setup db inside __init__.py
from project import db, login_manager
from flask_bcrypt import Bcrypt
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

bcrypt = Bcrypt()

class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password_hash = bcrypt.generate_password_hash(password)

    def check_password(self, password):
        return bcrypt.check_password_hash(self.password_hash, password)

class Task(db.Model):
    __tablename__ = 'tasks'

    id = db.Column(db.Integer, primary_key=True)
    task = db.Column(db.Text)
    owner = db.relationship('Owner', backref='tasks', uselist=False)

    def __init__(self, task):
        self.task = task

    def __repr__(self):
        if self.owner:
            return f"Task: #{self.id} - {self.task}. Added by {self.owner.name}"
        else:
            return f"Task: #{self.id} - {self.task}."

class Owner(db.Model):
    __tablename__ = 'owners'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    task_id = db.Column(db.Integer, db.ForeignKey('tasks.id'))

    def __init__(self, name, task_id):
        self.name = name
        self.task_id = task_id

project/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField

class AddForm(FlaskForm):
    name = StringField('Owner Name')
    task_id = IntegerField('Task Id')
    submit = SubmitField('Add Owner')

project/tasks/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField

class AddForm(FlaskForm):
    task = StringField('Task')
    submit = SubmitField('Add Task')

class DeleteForm(FlaskForm):
    id = IntegerField('Task Id')
    submit = SubmitField('Delete Task')

project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('password_confirm', message='Passwords must match')])
    password_confirm = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Register')

    def check_email(self, email):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('This email has already been registered.')

    def check_username(self, username):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username is not available.')

project/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

login_manager = LoginManager()

app = Flask(__name__)

# secret key setup
app.config['SECRET_KEY'] = 'secretkey'

# db setup
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:password@localhost/todoapp'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app, db)

login_manager.init_app(app)
login_manager.login_view = 'users.login'

# Import Blueprints
from project.owners.views import owners_blueprint
from project.tasks.views import tasks_blueprint
from project.users.views import users_blueprint

app.register_blueprint(owners_blueprint, url_prefix='/owners')
app.register_blueprint(tasks_blueprint, url_prefix='/tasks')
app.register_blueprint(users_blueprint, url_prefix='/users')

project/owners/views.py
from flask import Blueprint, render_template, redirect, url_for
from project import db
from project.models import Owner
from project.owners.forms import AddForm

owners_blueprint = Blueprint('owners', __name__, template_folder='templates/owners')

@owners_blueprint.route('/add', methods=['GET', 'POST'])
def add():
    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data
        task_id = form.task_id.data
        new_owner = Owner(name, task_id)
        db.session.add(new_owner)
        db.session.commit()

        return redirect(url_for('index'))

    return  render_template('add_owner.html', form=form)

project/tasks/views.py
from flask import Blueprint, render_template, redirect, url_for
from project import db
from project.models import Task
from project.tasks.forms import AddForm, DeleteForm

tasks_blueprint = Blueprint('tasks', __name__, template_folder='templates/tasks')

@tasks_blueprint.route('/add', methods=['GET', 'POST'])
def add():
    form = AddForm()
    if form.validate_on_submit():
        task = form.task.data
        new_task = Task(task)
        db.session.add(new_task)
        db.session.commit()

        return redirect(url_for('index'))

    return render_template('add.html', form=form)

@tasks_blueprint.route('/admin', methods=['GET', 'POST'])
def delete():
    form = DeleteForm()
    if form.validate_on_submit():
        id = form.id.data
        task = Task.query.get(id)
        db.session.delete(task)
        db.session.commit()

        return redirect(url_for('index'))

    return render_template('delete.html', form=form)

project/users/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, request
from project import db
from flask_login import login_user, login_required, logout_user
from project.models import User
from project.users.forms import LoginForm, RegistrationForm

users_blueprint = Blueprint('users', __name__, template_folder='templates/users')

@users_blueprint.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html')

@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You are logged out!")
    return redirect(url_for('index'))

@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("Logged in Successfully!")

            next = request.args.get('next')
            if next == None or not next[0] == '/' or next == '/users/logout':
                next = url_for('users.dashboard')

            return redirect(next)

    return render_template('login.html', form=form)

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        email = form.email.data
        username = form.username.data
        password = form.password.data
        user = User(email, username, password)

        db.session.add(user)
        db.session.commit()
        flash("Registration Successful!")
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)

project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Flask Todo</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a href="#" class="navbar-brand">FlaskTodo</a>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a href="{{url_for('index')}}" class="nav-link">Home</a>
      </li>
      <li class="nav-item">
        <a href="{{url_for('tasks.add')}}" class="nav-link">Add</a>
      </li>
      <li class="nav-item">
        <a href="{{url_for('tasks.delete')}}" class="nav-link">Admin</a>
      </li>
      <li class="nav-item">
        <a href="{{url_for('owners.add')}}" class="nav-link">Add Owner</a>
      </li>
      {% if current_user.is_authenticated %}
      <li class="nav-item">
        <a href="{{url_for('users.logout')}}" class="nav-link">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a href="{{url_for('users.login')}}" class="nav-link">Login</a>
      </li>
      <li class="nav-item">
        <a href="{{url_for('users.register')}}" class="nav-link">Register</a>
      </li>
      {% endif %}
    </ul>
  </nav>

  {% block content %}

  {% endblock %}

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

project/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row mt-4">
    <div class="col-md-12">
      <h2 class="text-center mb-4">Flask Todo App</h2>
      <div class="row justify-content-center">
        <div class="col-md-8">
          {% if all_tasks|length > 0 %}
          <ul class="list-group">
            {% for task in all_tasks %}
            <li class="list-group-item">{{task}}</li>
            {% endfor %}
          </ul>
          {% else %}
          <p class="text-center">You haven't added any task. Please add it to view all the tasks.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}